backend:
  name: github
  repo: YashwanthPandi/Portfolio-Website-DE
  branch: prod
  base_url: https://decap-cms-auth.pandiyashwanth-8d9.workers.dev
  auth_endpoint: /auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    # This matches your URL structure: /posts/YYYY/MM/title
    path: "{{year}}/{{month}}/{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", default: ["posts"] }
      - { label: "Body", name: "body", widget: "markdown" }